# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ea24ad258523524df5f0e8796fdaea47dc866748cc68c768e21c1522bb169fd1f7260855f432311309c495380aee03d1c43b837001763115a7eb61e1340848

test:
  secret_key_base: 5b44881c3ffe13662f432299625dd9002a361973812d57c3130d6cb257e91a5159a0ef7c972842e93ae233526f6c03c4dc1c6b3cb928b6d033e0a45a10b516f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
