# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).ready ->
  # init Isotope
  $grid = $('.grid').isotope(
    itemSelector: '.element-item'
    layoutMode: 'masonry'
    getSortData:
      name: '.name'
      symbol: '.symbol'
      number: '.number parseInt'
      category: '[data-category]'
      weight: (itemElem) ->
        weight = $(itemElem).find('.weight').text()
        parseFloat weight.replace(/[\(\)]/g, '')
  )
  # bind sort button click
  $('.sort-by-button-group').on 'click', 'button', ->
    sortValue = $(this).attr('data-sort-value')
    $grid.isotope sortBy: sortValue
    return
  # change is-checked class on buttons
  $('.button-group').each (i, buttonGroup) ->
    $buttonGroup = $(buttonGroup)
    $buttonGroup.on 'click', 'button', ->
      $buttonGroup.find('.is-checked').removeClass 'is-checked'
      $(this).addClass 'is-checked'
      return
    return
  return

# ---
# generated by js2coffee 2.2.0
