# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


$(document).ready ->
  # init Isotope
  $grid = $('.place-grid').isotope(
    itemSelector: '.card'
    layoutMode: 'masonry'	
    getSortData:
      name: '.name'
      symbol: '.symbol'
      number: '.number parseInt'
      category: '[data-category]'
      event: (itemElem) ->
        event = $(itemElem).find('.event').text()
        parseFloat event.replace(/[\(\)]/g, ''))

# filter functions
  filterFns = 
    numberGreaterThan50: ->
      number = $(this).find('.number').text()
      parseInt(number, 10) > 50
    ium: ->
      name = $(this).find('.name').text()
      name.match /ium$/
  # bind filter button click
  $('.filters-button-group').on 'click', 'button', ->
    filterValue = $(this).attr('data-filter')
    # use filterFn if matches value
    filterValue = filterFns[filterValue] or filterValue
    $grid.isotope filter: filterValue
    return
  # change is-checked class on buttons
  $('.button-group').each (i, buttonGroup) ->
    $buttonGroup = $(buttonGroup)
    $buttonGroup.on 'click', 'button', ->
      $buttonGroup.find('.is-checked').removeClass 'is-checked'
      $(this).addClass 'is-checked'
      return
    return
  



  return



# ---
# generated by js2coffee 2.2.0


